# Task A (The Proposal) Instructions {#taskA}

Task A requires you to accomplish the following:

On 2018-09-25, you will become part of a **group** of about five people, and your group will:

1. develop and propose 2-3 "research questions" for Study 1 (The Class Survey). Here, your research questions must clearly identify meaningful statistical comparisons.
2. propose 6-10 "homemade" survey questions for Study 1 that relate to your research questions, and
3. propose a "scale" for Study 1 that also relates to your research questions.

As an **individual**, you will also:

4. develop and propose a meaningful summary of your ideas and research question for Study 2 (Your Data). Your research question needs to clearly relate to modeling and prediction of a quantitative outcome on the basis of a set of predictor variables.
5. identify and present a detailed description of a data set that is likely to lead to an answer to the research question proposed for Study 2, and that is appropriate for use in this project.

The rest of this section contains guidance as to what sort of questions your group will need to propose for the class survey in Study 1, and as to what sorts of data sets and research questions are appropriate for your Study 2 proposal. 

## Deadline and Submission information

The project groups will only apply to Project Tasks A, C and D. You will become part of a project group on 2018-09-25 and the groups will disband after the survey is finalized in late October. 

Task A is due at noon on 2018-10-15. (**Note the change of date.**) You will submit your Task A work through [Canvas](https://canvas.case.edu/). 

- The group work (Parts 1-3) need to be submitted by one of the members of your group. 
    - If you are not the person submitting this information for your group, then your Task A submission should begin with the statement: "Parts 1-3 of Task A were submitted for my group by PERSON'S NAME."
- All students need to submit Parts 4 and 5 of Task A, individually. You can do this in advance of your group's submission of Parts 1-3 if you like.
- Please note that **Task A and Task B** are no longer due at the same time. Task B is due 2018-10-12, but Task A is now due 2018-10-15.

## Study 1 work for Task A

In Study 1, you will survey your fellow students through an online instrument (containing somewhere around 100 items) that we will develop in Tasks A, C and D in September and October and then administer in the final week of October (Task E). 

Students in the class will develop the items for this instrument in 10 groups of about 5 people per group. The final survey will include questions generated by each of the 10 groups in the class. 

The course survey will be done online, and the respondents (de-identified, of course) will include all students in the current 431 class, plus the teaching assistants, and perhaps some volunteers from previous iterations of the course, in an effort to get a reasonable (but by no means random or representative) sample of graduate students at CWRU. 

Remember that Study 1 is about making comparisons between groups.

### Research Questions

The first part of Task A requires your group to develop and propose 2-3 "research questions" for Study 1 (The Class Survey). 

> A research question is the fundamental core of a research project, study, or review of literature. It focuses the study, determines the methodology, and guides all stages of inquiry, analysis, and reporting. [Source](https://researchrundowns.com/intro/writing-research-questions/)

- The research questions your project group will prepare for Study 1 should state the study objective in terms that allow us to apply statistical methods to test data to obtain an answer.
- Each research question should be written in the form of a comparison of 2-3 exposures or groups in terms of an outcome. 
- At least one of your research questions needs to compare groups on a quantitative outcome, and at least one needs to compare groups on a categorical outcome (containing no more than 5 categories.)

Quoting Roger Peng, from [Exploratory Data Analysis with R](https://bookdown.org/rdpeng/exdata/):

> Formulating a question can be a useful way to guide the exploratory data analysis process and to limit the exponential number of paths that can be taken with any sizeable dataset. In particular, a sharp question or hypothesis can serve as a dimension reduction tool that can eliminate variables that are not immediately relevant to the question. For example, (suppose that we are interested in) looking at an air pollution dataset from the U.S. Environmental Protection Agency (EPA). 

> A general question one could ask is "Are air pollution levels higher on the east coast than on the west coast?" But a more specific question might be "Are hourly ozone levels on average higher in New York City than they are in Los Angeles?"

> Note that both questions may be of interest, and neither is right or wrong. But the first question requires looking at all pollutants across the entire east and west coasts, while the second question only requires looking at single pollutant in two cities. It's usually a good idea to spend a few minutes to figure out what is the question you're really interested in, and narrow it down to be as specific as possible (without becoming uninteresting).

### Research Questions that have worked in the past

For Study 1, your research questions will need to compare two or more exposure groups on a quantitative outcome (in one case) and on a categorical outcome (in another case). Here are several examples that worked in the past:

- "Do messy people tend to have higher levels of self-described creativity than organized people?"
- "Is whether you voted in the last presidential election strongly associated with your level of interest in the current election?"
- "Does being in a committed romantic relationship result in higher self-esteem compared to not being in a committed romantic relationship?"
- "Do conscientious people spend more time every week engaged in activities, such as exercise, thought to promote health and well-being compared to others?"
- "Do graduate students who routinely pack their lunch have a lower BMI than graduate students who routinely purchase their lunch?"
- "Do individuals who spend a lot of time on social media each day have more or less social anxiety than those who do not?"

Don't boil the ocean here. You're looking for a research question that can be reasonably addressed in a survey of approximately 50 people, so it has to be pretty straightforward.

#### Checklist for Research Questions

1. Is our research question (RQ) something that we are curious about and that others might care about? 
2. Does our RQ present an issue on which we can justify a stand prior to data collection about what we think will happen?
3. Is our RQ too broad, too narrow, or OK, given the time frame and restrictions of this survey?
4. Is our RQ measurable? What type of information do we need? Can I find a way to ask a limited number of survey questions in such a way to allow me to (after the data are collected) either support or contradict a position on my RQ? 
- Adapted from [this online tutorial from Empire State College](http://www8.esc.edu/htmlpages/writerold/menus.htm#develop)

#### Tips on Writing Good Research Questions

- [Duke](https://sites.duke.edu/urgws/files/2014/02/Research-Questions_WS-handout.pdf) has a nice overview online of key issues.
- [Vanderbilt](https://www.vanderbilt.edu/writing/wp-content/uploads/sites/164/2016/10/Formulating-Your-Research-Question.pdf) has some nice materials, built from the [tutorial at Empire State College](http://www8.esc.edu/htmlpages/writerold/menus.htm#develop) quoted earlier
- Jeff Leek provides several relevant tips in *The Elements of Data Analytic Style*
- https://researchrundowns.com/intro/writing-research-questions/ has some excellent tips on wording

### Specifying Survey Questions

The second part of Task A requires your group to develop and propose 6-10 "homemade" survey questions for Study 1 that relate to your research questions.

Your group will need to specify the exact wording for your survey questions (and potential answers for any categorical responses.) This will likely require some editing and rework, once we have the complete set of proposed questions from all students. Be prepared to revise and resubmit, quickly, so that all items can be resolved in time for publication of the draft survey.

Of your 6-10 survey questions ...

- at least two should ask the respondents to provide you with a **number** that expresses a quantitative outcome of interest to you, and these outcomes should relate closely to at least one of your research questions.
    - If you are asking people to respond to a prompt using a rating, that rating should be expressed on a wide scale. Our preference is a 0-100 scale for quantitative items, where 0 represents the most negative reaction and 100 the most positive reaction to the item. 
    - One common choice is to make a statement and ask for agreement with that statement on a scale from 0 = Strongly Disagree to 100 = Strongly Agree. 
    - The reason we prefer a 0-100 scale is to increase variation in our responses, as compared to, say, a 1-10 scale. 
    - When responding to items using a scale like this on the actual survey, please use the whole scale.
- **at least two** should ask the respondents to provide you with a response that expresses a categorical outcome of interest to you, and these, too, should relate to at least one of your   research questions.
    - You will need to specify each of the available responses that you wish to use in the survey. 
    - No more than five options for your categorical outcome, please.
    - The response options you specify should be mutually exclusive and collectively exhaustive.
- **at least two** should ask the respondents to categorize themselves into one of two (or three) groups. 
    - Be aware that you will need to have at least 10 students in each group in order to build a semi-reasonable analysis.
    - You should expect that 50-55 people will actually respond to the survey, in total. 
    - Again, these groupings should be linked to your research questions.

You are welcome to submit exactly 6, or as many as 10 total survey questions in this part of the Task. It is likely that some of your survey questions will not correspond to some of your research questions, and that's OK, but each survey question should be linked to at least one of your research questions.

#### Dr. Love will include 15 Survey Questions Automatically

The following items will be included in the survey to identify "groups" of students in a reasonable way. As a result, you should not ask these questions in your proposed list, although you can and should consider whether these groupings would be good candidates for application to your research questions.

The following 7 items will have yes/no responses, and thus produce binary groups for analysis.

1. Were you born in the United States? 
2. Is English the language you speak better than any other? 
3. Do you identify as female?
4. Do you wear prescription glasses or contact lenses?
5. Before taking 431, had you ever used R before?
6. Are you currently married or in a stable domestic relationship?
7. Have you smoked 100 cigarettes or more in your entire life?

The next eight items generate non-binary responses. Together, after the survey is complete, we will identify "cutpoints" for these eight items to identify groups of meaningful size. 

8. In what year were you born?
9. How would you rate your current health overall (Excellent, Very Good, Good, Fair, Poor)
10. For how long, in months, have you lived in Northeast Ohio?
11. What is your height in inches? (If you are five feet, eight inches tall, please write 68 inches. To convert from centimeters to inches, multiply your height in centimeters by 0.3937, and then round the result to the nearest inch.)
12. What is your weight in pounds? (To convert from kilograms to pounds, multiply your weight in kilograms by 2.2046, and then round the result to the nearest pound.)
13. What is your pulse rate, in beats per minute? (Please either use a tracking device, or count your pulse for 15 seconds then multiply by 4)
14. Last week, on how many days did you exercise? (0 - 7)
15. Last night, how many hours of sleep did you get?

#### Permitted Types of Items

The survey will be conducted using a Google Form, rather than Survey Monkey or some other tool. Thus, we have a somewhat restricted set of item types.

For **quantitative measures**, Google Forms permit the use of

1. a *short answer* item without any restrictions on the response (except a character limit)
2. a *short answer* item where respondents are forced to insert a number within a given range through a validation process that only accepts the response if it falls within the specified limits.
3. *linear scale* items for ordered categorical ratings (but only on a scale of up to ten points - i.e. 1 to 10)

For **categorical measures**, Google Forms permit the use of 

1. *multiple choice* items for endorsing a single choice from a group of 2-10 alternatives.
2. *checkbox* items for the endorsement of one or more choices from a group of 2-10 alternatives.
3. *linear scale* items for ordered categorical ratings (often on a 1-X scale, where X is between 2 and 10)
4. *dropdown* items for selections of one option from a group of 2-3 choices.

#### Old Class Surveys

The surveys (each containing at least 100 items) from [2014](https://github.com/THOMASELOVE/431-2018-project/blob/master/oldsurveys/2014_431_class_survey.pdf), [2015](https://github.com/THOMASELOVE/431-2018-project/blob/master/oldsurveys/2015_431_class_survey.pdf), [2016](https://github.com/THOMASELOVE/431-2018-project/blob/master/oldsurveys/2016_431_class_survey.pdf) and [2017](https://github.com/THOMASELOVE/431-2018-project/blob/master/oldsurveys/2017_431_class_survey.pdf) are available as PDF documents on our web site.

Remember that the rules used this year have been modified from what has been used for the project previously.


### Specifying a "Scale"

The third part of Task A requires your group to identify and propose a "scale" of items for Study 1 (The Class Survey). 

Your group needs to specify a published scale (available for free public use) to generate an outcome or grouping(s) of interest from those completing the survey. You will have to provide a complete reference to the scale (online, ideally) and specify each of the items in the scale, and how the scale is then evaluated, in all necessary detail to allow us to review and replicate the scale in practice. 

The word "scale" is used in many different ways. In this case, by a scale I mean a published list of items, usually accompanied by a scoring rubric that provides some sort of composite score or scores. Examples of scales we have used in the past include:

- Two [Health Consciousness Scales](https://chirr.nlm.nih.gov/health-orientation.php), one due to Gould another to Dutta-Bregman [Gould Health Consciousness Scale](https://chirr.nlm.nih.gov/health-orientation.php)
- The [Ten-Item Personality Inventory](https://gosling.psy.utexas.edu/scales-weve-developed/ten-item-personality-measure-tipi/ten-item-personality-inventory-tipi/)
- The [Perceived Stress Scale](https://das.nh.gov/wellness/Docs/Percieved%20Stress%20Scale.pdf)
- The [Epworth Sleepiness Scale](https://www.sleepapnea.org/assets/files/pdf/ESS%20PDF%201990-97.pdf)

Your group will need to verify explicitly in your Task A materials that the scale your group proposes is freely available for use by anyone, without any fees or registration requirements.

## Study 2 Work for Task A

You, individually, will present a proposal **summary** (< 300 words) and a brief **data description** for Study 2 in Task A.

You will be building a multiple linear regression model, and using it to predict your outcome of interest. 

### The Proposal Summary

The fourth part of Task A is to develop and propose a meaningful summary of your ideas and research question for Study 2 (Your Data).

Your summary should begin with a title for your Study 2. Take the time to come up with a good, interesting title. You are going to work hard on this thing; please resist the temptation to kill my interest at the start by calling it "431 Statistics Project" or anything else that shows a similar lack of effort.

Provide me a very brief summary of what you're trying to accomplish - specifically, what your research question is, and what you hypothesize will happen.

The five most important things to do in the summary are:

1. Write clearly. My best advice is to finish the summary as soon as you can, and then give it to someone else to read, who can criticize it for lack of clarity in the writing. 
2. Specify the topic of interest, and motivate your study of it.
3. Explicitly specify your key research question, which should be stated as a question, and which should clearly and naturally lead to a prediction model for a quantitative outcome.
4. Explain what you hypothesize will happen, and
5. Explicitly link your key research question to the data set you describe in your data description.
        
The summary is the heart of the proposal, and requires some care. You will need to convince me that your topic is interesting, your data are relevant, and building a model and making predictions of a quantitative outcome using the predictors available to you will be worthwhile.

- The summary ends with a statement of the research question or questions (you may have one, or possibly two.) An excellent question conveys the main objective of the study in terms that allow us to apply statistical models to describe an association between one or more predictors and a quantitative outcome. Some advice on writing a good research question is provided below, after the data set description information.
- It should be possible for me to explain your study accurately just by reading this summary. If it's not possible, it will come back to you for a REDO. Statistics is a details business. Get the details right.
- This summary should be less than 300 words.
- Use complete English sentences. Write in plain language. Use words we all know. Avoid jargon. And [look at the general suggestions about writing in the Course Syllabus](https://thomaselove.github.io/2018-431-syllabus/a-few-general-writingpresenting-tips.html).

### The Data Description

Your data description can be as long as it needs to be, although two pages is usually more than enough. It should include:

1. Your data source, which can be an online source (in which case include a working link), a published paper or journal article (in which case I need a link and a PDF copy of the paper), or unpublished data (in which case I need the details of how the data were gathered).

2. A thorough description of the data collection process, with complete details as to the nature of the variables, the setting for data collection, and complete details of any apparatus you used which may affect results.

3. Specification of the people and methods involved.
    + Who are the subjects under study? 
    + When were the data gathered? By whom?
    + How many subjects are included?
    + What caused subjects to be included or excluded from the study?

4. Your planned **quantitative** outcome, which must relate directly to the research question you specified above. Provide a complete definition, including specifying the exact wording of the question or details of the measurement procedure used to obtain the outcome. If available, you can also include descriptions of secondary **quantitative** outcomes. Your outcomes must be quantitative in Study 2.

5. Your predictors of interest, which should also relate to the research question in an obvious way. Again, define the variables carefully, as you did with the outcome.

6. If you already have the data, tell me that. If you don't, specify any steps you must still take in order to get the data, and specify the date by which you will have your data (must be no later than November 1.)

### Data Restrictions

Study 2 data sets MUST 

- contain between 250 and 250,000 distinct observations,
- contain at least one quantitative outcome variable,
- contain at least four predictor variables, one of which may be identified as the "key" predictor of interest,
- include at least one quantitative predictor variable, and at least one categorical predictor variable,
- include a complete description of how the data were gathered, so that information must be publicly available,
- be in your hands no later than November 1, 
- be shared data with a statistician (Dr. Love) following [Jeff Leek's guide to sharing data with a statistician](https://github.com/jtleek/datasharing) as part of Task F. This means you need to have access to the data in the raw, and it means that I have to be able to have access to it in the raw, as well. - be capable of being fully cited for any and all data elements, including a complete codebook, as this must be provided as part of your proposal.

While there are some great resources available to some people in this class by virtue of their affiliation with one of the health systems in town, I can do nothing to get you access to health system specific data as part of your project for this class or for 432, and in general, data from those sources are not especially appropriate because of issues with protected health information.

No more than two students in the class can work on the same data. If two of you have data you would each like to work on, that may be OK, but you'll need to generate separate research questions and perform your analyses and the Project Tasks separately.

I am not interested in you using pre-cleaned data from an educational repository, such as:

+ [this one at the Cleveland Clinic](http://www.lerner.ccf.org/qhs/datasets/), or [this one at Vanderbilt University](http://biostat.mc.vanderbilt.edu/wiki/Main/DataSets), or [this one at UCLA](http://www.stat.ucla.edu/projects/datasets/), or [this one at the University of Florida](http://www.stat.ufl.edu/~winner/datasets.html), or [this one at Florida State University](http://people.sc.fsu.edu/~jburkardt/datasets/datasets.html), or
+ [StatLib at Carnegie-Mellon University](http://lib.stat.cmu.edu/datasets/), or [the Journal of Statistics Education Data Archive](http://www.amstat.org/publications/jse/jse_data_archive.htm), or 
+ the data sets gathered in the fivethirtyeight package, the mosaic package, the cars package, the datasets package, or any other R package designed primary for teaching, or 
+ [StatSci.org's repository of textbook examples and ready for teaching data](http://www.statsci.org/datasets.html), or
+ any of the many textbook-linked repositories of data sets, like [this one for Statistics: Unlocking the Power of Data](http://www.lock5stat.com/datapage.html), or
+ any similar repository Professor Love deems to be inappropriate

### Some Potentially Useful Data Sources

The ideal choice of data source for this project is a public-use version of a meaningful data set without access restrictions. With so many students in the class, I cannot be responsible for supervising your work with restricted data personally. Some appealing sources to explore include:

- the new [Google Datasets Search](https://toolbox.google.com/datasetsearch)
- https://www.data.gov/ The home of the U.S. Government's open data
- http://www.census.gov/data.html The U.S. Census Bureau has many interesting data sets, including the [Current Population Survey](http://www.census.gov/programs-surveys/cps.html)
- http://www.healthdata.gov/ 125 years of U.S. Health Care Data
- http://www.cdc.gov/nchs/nhanes/index.htm National Health and Nutrition Examination Survey. 
    + You may want to look at [the nhanesA package in R](https://cran.r-project.org/web/packages/nhanesA/vignettes/Introducing_nhanesA.html)
- http://dashboard.healthit.gov/datadashboard/data.php Office of the National Coordinator for Health IT's dashboard
- http://www.icpsr.umich.edu/icpsrweb/ ICSPR (Inter-university Consortium for Political and Social Research) is a source for many public-use data sets
    + This includes the [Health and Medical Care data archive of the Robert Wood Johnson Foundation](http://www.icpsr.umich.edu/icpsrweb/HMCA/)
- http://gss.norc.org/ The General Social Survey
- http://www.bls.gov/data/ Bureau of Labor Statistics
- http://nces.ed.gov/surveys/ National Center for Education Statistics
- http://www.odh.ohio.gov/healthstats/dataandstats.aspx Ohio Department of Health
- http://open.canada.ca/en Canada Open Data
- http://digital.nhs.uk/home Health data sets from the UK National Health Service.
- http://www.who.int/en/ World Health Organization
- http://www.unicef.org/statistics/ UNICEF has some available data on women and children
- http://www.pewinternet.org/datasets/ Pew Research Center's Internet Project
- http://portals.broadinstitute.org/cgi-bin/cancer/datasets.cgi Broad Institute's Cancer Program
- http://www.kdnuggets.com/datasets/index.html is a big index of lots of available data repositories
- https://www.kaggle.com/ Kaggle competition data sets are attractive to students occasionally, but I've seen a lot of them before and don't really want to see them again.

I cannot guarantee the quality of any of the data sets available at these sites, but I've spent at least a little time at many of them in recent months.

### If you are storing your own data

An extremely useful link for those of you **building a spreadsheet to store data** is [Karl Broman's tutorial](http://kbroman.org/dataorg/) on the subject. No one was born knowing this stuff - take a look.

## Research Questions for Study 2 that worked well in the past

For Study 2, your research questions will need to fit within the confines of a regression model, where a quantitative outcome is predicted using a series of at least four predictor variables. In many cases, a key predictor will be of primary interest, with other predictors serving to "adjust" away noise and generate fairer comparisons. Here are a few examples from past classes:

- "Is the presence of cardiovascular risk factors, specifically elevated hemoglobin A1c, predictive of cognitive impairment as defined by the Digit Symbol Substitution Test in patients over the age of 60 years, after adjusting for age, education, and depression?"
- "What is the effect of thyroid dysfunction on LDL level after adjusting for age, sex, and level of physical activity in the population of patients at XXXXXXXX location who are 40 years-old and above?"
- "Do conscientiousness and openness predict more conservative or liberal attitudes about government spending and whether and how much wasteful spending exists, after accounting for age, income and professional status?"
- "Does overweight or obesity (defined by body mass index) predict insulin resistance (measured by the homeostasis model assessment of insulin resistance (HOMA-IR)) in young adults with first-time acute coronary syndrome after adjusting for age, sex, race/ethnicity and severity of (several comorbid conditions)?"

## Evaluating Task A

Dr. Love will evaluate all proposals (Task A) personally, in the order in which they are received. Proposals will receive one of two grades: OK or REDO. That grade will be posted to Canvas. REDO will be accompanied with specific requests in the form of a Canvas comment that should be accomplished within a short time window (approximately 24 hours). If you materially deviate from these specifications, Dr. Love will not evaluate your proposal other than to re-specify what needs to be fixed before he will respond.

- A score of OK is worth 10/10 points for Task A, once Task B is also complete. 
- You (and/or your group, if there are problems with parts 1-3) must REDO the Proposal until you reach OK. Sometimes, that's more than once.

