# Task B (Presentation Sign-Up) Instructions {#taskB}

## Deadline and Submission information

Task B is due at noon on 2018-10-12. Submit your Task B work by completing the Google Form linked at http://bit.ly/431-2018-project-signup-taskB.

- Please note that Task A is also due at the same time.

- All students must specify a minimum of 8 time slots, on at least two different days, when they can give their presentation. 
- You will also be able to specify your two favorite time slots among those you have chosen.
- The presentation dates are 2018-12-10, 2018-12-11 and 2018-12-13.
    - University classes end December 7. 
    - December 10 is one of the official University Reading Days, and December 11 and 13 are Final Exam Days.
- If you have some special problem or concern or need to give your presentation before 2018-12-10, there is a space to tell Dr. Love about that at the end of the form.

## Available Time Slots

There are 55 available time slots, listed below.

### Monday 2018-12-10 morning

- Time Slot	1	MON	10-Dec	from	8:00 AM	to	8:20 AM	, so you would arrive at 	7:50 AM
- Time Slot	2	MON	10-Dec	from	8:25 AM	to	8:45 AM	, so you would arrive at 	8:15 AM
- Time Slot	3	MON	10-Dec	from	8:50 AM	to	9:10 AM	, so you would arrive at 	8:40 AM
- Time Slot	4	MON	10-Dec	from	9:15 AM	to	9:35 AM	, so you would arrive at 	9:05 AM
- Time Slot	5	MON	10-Dec	from	9:40 AM	to	10:00 AM, so you would arrive at 	9:30 AM
- Time Slot	6	MON	10-Dec	from	10:15 AM to	10:35 AM, so you would arrive at 	10:05 AM
- Time Slot	7	MON	10-Dec	from	10:40 AM to	11:00 AM, so you would arrive at 	10:30 AM
- Time Slot	8	MON	10-Dec	from	11:05 AM to	11:25 AM, so you would arrive at 	10:55 AM
- Time Slot	9	MON	10-Dec	from	11:30 AM to	11:50 AM, so you would arrive at 	11:20 AM
- Time Slot	10	MON	10-Dec	from	12:35 PM to	12:55 PM, so you would arrive at 	12:25 PM

### Monday 2018-12-10 afternoon

- Time Slot	11	MON	10-Dec	from	1:00 PM	to	1:20 PM	, so you would arrive at 	12:50 PM
- Time Slot	12	MON	10-Dec	from	1:25 PM	to	1:45 PM	, so you would arrive at 	1:15 PM
- Time Slot	13	MON	10-Dec	from	1:50 PM	to	2:10 PM	, so you would arrive at 	1:40 PM
- Time Slot	14	MON	10-Dec	from	2:15 PM	to	2:35 PM	, so you would arrive at 	2:05 PM
- Time Slot	15	MON	10-Dec	from	2:40 PM	to	3:00 PM	, so you would arrive at 	2:30 PM
- Time Slot	16	MON	10-Dec	from	3:15 PM	to	3:35 PM	, so you would arrive at 	3:05 PM
- Time Slot	17	MON	10-Dec	from	3:40 PM	to	4:00 PM	, so you would arrive at 	3:30 PM
- Time Slot	18	MON	10-Dec	from	4:05 PM	to	4:25 PM	, so you would arrive at 	3:55 PM
- Time Slot	19	MON	10-Dec	from	4:30 PM	to	4:50 PM	, so you would arrive at 	4:20 PM
- Time Slot	20	MON	10-Dec	from	4:55 PM	to	5:15 PM	, so you would arrive at 	4:45 PM

### Tuesday 2018-12-11 morning

- Time Slot	21	TUE	11-Dec	from	8:00 AM	to	8:20 AM	, so you would arrive at 	7:50 AM
- Time Slot	22	TUE	11-Dec	from	8:25 AM	to	8:45 AM	, so you would arrive at 	8:15 AM
- Time Slot	23	TUE	11-Dec	from	8:50 AM	to	9:10 AM	, so you would arrive at 	8:40 AM
- Time Slot	24	TUE	11-Dec	from	9:15 AM	to	9:35 AM	, so you would arrive at 	9:05 AM
- Time Slot	25	TUE	11-Dec	from	9:40 AM	to	10:00 AM, so you would arrive at 	9:30 AM
- Time Slot	26	TUE	11-Dec	from	10:15 AM to	10:35 AM, so you would arrive at 	10:05 AM
- Time Slot	27	TUE	11-Dec	from	10:40 AM to	11:00 AM, so you would arrive at 	10:30 AM
- Time Slot	28	TUE	11-Dec	from	11:05 AM to	11:25 AM, so you would arrive at 	10:55 AM
- Time Slot	29	TUE	11-Dec	from	11:30 AM to	11:50 AM, so you would arrive at 	11:20 AM

### Tuesday 2018-12-11 afternoon

- Time Slot	30	TUE	11-Dec	from	12:35 PM to	12:55 PM, so you would arrive at 	12:25 PM
- Time Slot	31	TUE	11-Dec	from	1:00 PM	to	1:20 PM, so you would arrive at 	12:50 PM
- Time Slot	32	TUE	11-Dec	from	1:25 PM	to	1:45 PM, so you would arrive at 	1:15 PM
- Time Slot	33	TUE	11-Dec	from	1:50 PM	to	2:10 PM, so you would arrive at 	1:40 PM
- Time Slot	34	TUE	11-Dec	from	2:15 PM	to	2:35 PM, so you would arrive at 	2:05 PM
- Time Slot	35	TUE	11-Dec	from	2:40 PM	to	3:00 PM, so you would arrive at 	2:30 PM
- Time Slot	36	TUE	11-Dec	from	3:15 PM	to	3:35 PM, so you would arrive at 	3:05 PM

### Thursday 2018-12-13 morning

- Time Slot	37	THU	13-Dec	from	8:00 AM	to	8:20 AM, so you would arrive at 	7:50 AM
- Time Slot	38	THU	13-Dec	from	8:25 AM	to	8:45 AM, so you would arrive at 	8:15 AM
- Time Slot	39	THU	13-Dec	from	8:50 AM	to	9:10 AM, so you would arrive at 	8:40 AM
- Time Slot	40	THU	13-Dec	from	9:15 AM	to	9:35 AM, so you would arrive at 	9:05 AM
- Time Slot	41	THU	13-Dec	from	9:40 AM	to	10:00 AM, so you would arrive at 	9:30 AM
- Time Slot	42	THU	13-Dec	from	10:15 AM to	10:35 AM, so you would arrive at 	10:05 AM
- Time Slot	43	THU	13-Dec	from	10:40 AM to	11:00 AM, so you would arrive at 	10:30 AM
- Time Slot	44	THU	13-Dec	from	11:05 AM to	11:25 AM, so you would arrive at 	10:55 AM
- Time Slot	45	THU	13-Dec	from	11:30 AM to	11:50 AM, so you would arrive at 	11:20 AM

### Thursday 2018-12-13 afternoon

- Time Slot	46	THU	13-Dec	from	12:35 PM to	12:55 PM, so you would arrive at 	12:25 PM
- Time Slot	47	THU	13-Dec	from	1:00 PM	to	1:20 PM, so you would arrive at 	12:50 PM
- Time Slot	48	THU	13-Dec	from	1:25 PM	to	1:45 PM, so you would arrive at 	1:15 PM
- Time Slot	49	THU	13-Dec	from	1:50 PM	to	2:10 PM, so you would arrive at 	1:40 PM
- Time Slot	50	THU	13-Dec	from	2:15 PM	to	2:35 PM, so you would arrive at 	2:05 PM
- Time Slot	51	THU	13-Dec	from	2:40 PM	to	3:00 PM, so you would arrive at 	2:30 PM
- Time Slot	52	THU	13-Dec	from	3:15 PM	to	3:35 PM, so you would arrive at 	3:05 PM
- Time Slot	53	THU	13-Dec	from	3:40 PM	to	4:00 PM, so you would arrive at 	3:30 PM
- Time Slot	54	THU	13-Dec	from	4:05 PM	to	4:25 PM, so you would arrive at 	3:55 PM
- Time Slot	55	THU	13-Dec	from	4:30 PM	to	4:50 PM, so you would arrive at 	4:20 PM

