# Task E (Taking the Survey) Instructions {#taskE}

## Deadline and Submission information

Task E is due at noon on 2018-11-02. Submit your answers to the course survey via the Google Form linked at http://bit.ly/431-2018-survey. That link will go live no later than noon on 2018-10-29.

- The final item asks for your name, and the system is collecting your email address (you must be logged into Google via CWRU). These will be pruned from the survey before data sets are created.
    - You should answer all of the items. Please don't skip any items you can answer. Your colleagues need data.
    - If you want to save your work and return later, note that only the *first* item in each section of the survey must be completed for Google to let you submit your work. Once you've submitted a partially completed survey, you can return as often as you like before the deadline to finish up.
- Note that Project Task D is due at the same time.

## Receiving Your Study 1 Data (early November)

Once the Survey is complete, we will post **multiple** data files, each containing some of the variables you need.

- You will need to download both files, and then *combine* and tidy to suit your needs. Combining data sets like this is a skill you'll need to master to successfully complete the Project.
- The files will be linked by the subject `id` number. 

