--- 
title: "431 Project Instructions"
author: "Thomas E. Love"
date: "Version: `r Sys.time()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: thomaselove/431-2018-project
description: "These are the instructions for the 431 project portfolio in Fall 2018."
---

# Overview {-}

This website contains the Fall 2018 project information for PQHS / CRSP / MPHP 431: Statistical Methods in Biological & Medical Sciences, Section 1. 

- All materials related to the project (including these instructions) are maintained and linked at https://github.com/THOMASELOVE/431-2018-project. 
- The direct link to this document is https://thomaselove.github.io/431-2018-project.

## Your Project includes Two Studies {-}

Your final project for this course will result in a portfolio of work related to two studies.

**Study 1 - Class Survey**. In the first study, you (sometimes working individually, sometimes in a group) will design, administer, analyze and present the results of a survey designed to compare two or three groups of subjects on some *categorical* and *quantitative* outcomes we will develop from your initial ideas.

**Study 2 - Your Data**. In the second study, you (working individually) will propose a research question and relevant data of interest to you, and then complete all elements of a data science project designed to create a statistical model for a *quantitative* outcome, then use it for prediction and assess the quality of those predictions.

## You have Eight Tasks to Complete this Semester {-}

The project involves two analyses (one for the class survey and one for your personal study), and a total of 8 tasks (deliverables.) Each task is to be completed by **12 NOON** on the specified date.

- [Task A (The Proposal)](#taskA) is due at noon on 2018-10-12, via [Canvas](https://canvas.case.edu/).
- [Task B (Presentation Sign-Up)](#taskB) is **also** due at noon on 2018-10-12, at http://bit.ly/431-2018-project-signup-taskB
- [Task C (Survey Editing)](#taskC) involves group work and is due at noon on 2018-10-23, via [Canvas](https://canvas.case.edu/).
- [Task D (Survey Comparison Plan)](#taskD) is **also** due at noon on 2018-10-23, at http://bit.ly/431-2018-survey-comparison-plan-taskD.
- [Task E (Taking the Survey)](#taskE) is due at noon on 2018-10-31
- [Task F (Sharing Study 2 Data)](#taskF) is due at noon on 2018-11-14, via [Canvas](https://canvas.case.edu/).
- [Task G (The Portfolio)](#taskG) is due at noon on 2018-12-13, via [Canvas](https://canvas.case.edu/).
- [Task H (Your Presentation)](#taskH) will be held on 2018-12-10, 2018-12-11 or 2018-12-13 in Dr. Love's office (Wood WG 82-L).

The bulk of this document contains specific instructions for each of these tasks.

## Working with This Document {-}

1. This document is broken down into multiple sections. Use the table of contents at left to navigate. 
2. At the top of the document, you'll see icons which you can click to 
    - search the document, 
    - change the size, font or color scheme of the page, and 
    - download a PDF or EPUB (Kindle-readable) version of the entire document.
3. The document is a work in progress, and will be updated occasionally through the semester. Check the Version information above to verify the last update time^[Note that the ePub and PDF versions will show slightly different times (but on the same day) as the HTML version.].

## Need Help? {-}

Questions about the project or the course can be directed to **431-help at case dot edu** or to Dr. Love directly at `thomas dot love at case dot edu`.

- The course home page is at https://github.com/THOMASELOVE/431-2018

